#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android.Resource", IsApplication=true)]

namespace Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MatrixExtensions.Android.Resource.String.ApplicationName = global::Android.Resource.String.ApplicationName;
			global::MatrixExtensions.Android.Resource.String.Hello = global::Android.Resource.String.Hello;
			global::RandomExtensions.Android.Resource.String.ApplicationName = global::Android.Resource.String.ApplicationName;
			global::RandomExtensions.Android.Resource.String.Hello = global::Android.Resource.String.Hello;
			global::ResolutionBuddy.Android.Resource.String.ApplicationName = global::Android.Resource.String.ApplicationName;
			global::ResolutionBuddy.Android.Resource.String.Hello = global::Android.Resource.String.Hello;
			global::Vector2Extensions.Android.Resource.String.ApplicationName = global::Android.Resource.String.ApplicationName;
			global::Vector2Extensions.Android.Resource.String.Hello = global::Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int logo = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int PlaceHolderIcon = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int SplashFile = 2130771970;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F020000
			public const int ApplicationName = 2130837504;
			
			// aapt resource value: 0x7F020002
			public const int app_name = 2130837506;
			
			// aapt resource value: 0x7F020001
			public const int Hello = 2130837505;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F030000
			public const int Theme_Splash = 2130903040;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
