name: Build signed aab for release

on:
  push:
    branches: [master, release/*, develop]

  # allow running this workflow manually
  workflow_dispatch:

jobs:
  generate-signed-aab:
    runs-on: windows-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Android project and sign generated aab
        uses: igotinfected-ci/build-and-sign-monogame-android@v1
        with:
          solution-path: '${{ github.workspace }}\CrawlIT\CrawlIT.sln'
          content-mgcb-path: '${{ github.workspace }}\CrawlIT\Android\Content'
          project-path: '${{ github.workspace }}\CrawlIT\Android'
          csproj-path: '${{ github.workspace }}\CrawlIT\Android\Android.csproj'
          build-configuration: "Release"
          package-format: "aab"
          keystore: ${{ secrets.KEYSTORE }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
