name: Run checks after push

on:
  push:
    branches: [master, release/*, develop]

  # allow running this workflow manually
  workflow_dispatch:

jobs:
  android-build-check:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build android project
        uses: igotinfected-ci/build-monogame@v2
        with:
          solution-path: '${{ github.workspace }}\CrawlIT\CrawlIT.sln'
          content-mgcb-path: '${{ github.workspace }}\CrawlIT\Android\Content'
          content-mgcb-platform: "Android"
          project-path: '${{ github.workspace }}\CrawlIT\Android'
          csproj-path: '${{ github.workspace }}\CrawlIT\Android\Android.csproj'
          build-target: "PackageForAndroid"
          build-configuration: "Release"
